# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # build VM on this box
  config.vm.box = "bento/ubuntu-16.04"
  
  # port forwarding from host to VM
  [ "4243","4440","3306","8080","8081","9000"].each do |port|
      config.vm.network "forwarded_port", guest: port, host: port
  end
  
  # use a private network for VMs to communicate
  config.vm.network "private_network", ip: "192.168.33.10"

  # fix for "stdin: is not a tty" and "ttyname: inappropriate ioctl for device"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # virtualbox customizaations and settings
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansiblebox"
    vb.memory = "512"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install software-properties-common -y > /dev/null 2>&1
    apt-add-repository ppa:ansible/ansible
    apt-get install ansible -y > /dev/null 2>&1
  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../playbook.yml"
		ansible.verbose = "vvv"
  end
end
